### ISSUE TITLE
GUI 2 icon colouring

### ISSUE THREAD

**Issue by jharris-westpac** [WestpacCXTeam/Angular-GUI#1]
I have having a go at implementing GEL 2 in a new base project but I am having trouble figuring out how to set the fill colour on an icon. 

I was suggested this:

.icon.icon-remove .icons-background {
            fill: green;
        }

<span class="icon icon-size-lg icon-remove" data-grunticon-embed></span> 

However this does not seem to have any effect? Not sure what .icons-background is? Maybe I am doing something wrong with how I embed it? I can see the icon but its black and white. 

Any ideas?

**Comment by jharris-westpac** [comment]
I have found the source of the issue after a few hours of investigation. Again this issue is caused because Grunticon has issues with SPA websites https://github.com/filamentgroup/grunticon/issues/258 

Basically it fires on document.ready state and does not embed the icons in an AngularJS app.  

This is a tricky one, but I may look at creating a directive just for icons as I think this is the only way but I am reverse engineering the grunticon lib and there is no unminified version. I did find this page referenced from that issue above however https://github.com/filamentgroup/grunticon#grunticon-loader-methods where we will need to call getIcons and embedIcons each time a section of the page changes (HTML is injected into the page) so that we can embed any new icons. 

We require the SVG to be directly embedded into the HTML in order for us to colour the icon using CSS. 

Once we have the SVG embedded, the CSS rule below will work properly. This brings up another point, instead of using grunticon, is it possible to have the GUI 2 blender output the SVG images as well? This is one alternative to using grunticon to embed, as we could embed them manually. As for colouring non SVG compliant browser icons, i.e. PNG’s, I think we have no chance.

**Comment by jharris-westpac** [comment]
Implemented refactored TypeScript version of the GruntIcon Angular Directive as part of https://github.com/WestpacCXTeam/GUI-source/issues/144 

Improved with caching support to avoid reloading / parsing the CSS for each icon. 

``` javascript
    /**
     * Embeds GruntIcon SVG into the HTML markup correctly
     */
    coreDirectives.directive('grunticonEmbed', function($window: ng.IWindowService) {

        // Cache grunticon properties so we dont reload them for each icon on the page
        var href: string;
        var iconCss: string;
        var iconObj: Object;

        return {
            restrict: 'A',
            scope: false,
            link: function ($scope: IGruntIconEmbedScope, $element: ng.IAugmentedJQuery, $attr: ng.IAttributes) {

                href    = href || $window.grunticon.href;
                iconCss = iconCss || $window.grunticon.getCSS(href);
                iconObj = iconObj || $window.grunticon.getIcons(iconCss);

                $window.grunticon.embedIcons(iconObj);
            }
        };
    });
```

**Comment by jharris-westpac** [comment]
I found additional issues with the above code where grunticon embedIcons is misbehaving. If you have another embedded SVG on the page such as a radio button grunticon replaces its SVG background also in error and that breaks radios entirely. Grunt icon code is inefficient, buggy, minified and obfuscated so there is no way forward using their library. 

I decided to write a new directive avoiding the broken grunticon code entirely and now far more efficient as it does not rescan the entire dom and reload CSS. It now works along side radio buttons and checkboxes found in the GUI without conflicts. 

``` javascript
    /**
     * Embeds GruntIcon SVG into the HTML markup correctly
     */
    coreDirectives.directive('grunticonEmbed', function($window: ng.IWindowService) {

        return {
            restrict: 'A',
            scope: false,
            link: function ($scope: IGruntIconEmbedScope, $element: ng.IAugmentedJQuery, $attr: ng.IAttributes) {

                if($window.grunticon.method === 'svg') {

                    var backgroundSvg = $window.decodeURIComponent(
                        $element.css('background-image').slice(4, -1).replace(/"/g, "")
                    ).split(',')[1];

                    $element.html(backgroundSvg);
                    $element.css('background-image','none');
                }
            }
        };
    });
```

**Comment by dominikwilkowski** [comment]
great job @jharris-westpac 
You should submit a PR to grunticon itself. They'd be happy to get the fixes in.

**Comment by tonytwong** [comment]
You could completely remove dependency on grunticon by ensuring only image/svg+xml can be replaced 

``` javascript
 /**
   * Embeds GruntIcon SVG into the HTML markup correctly
   */
coreDirectives.directive('grunticonEmbed', function($window: ng.IWindowService) {
    return {
        restrict: 'A',
        scope: false,
        link: function ($scope: IGruntIconEmbedScope, $element: ng.IAugmentedJQuery, $attr: ng.IAttributes) {
            var backgroundSvg = $window.decodeURIComponent(
                $element.css("background-image").slice(4, -1).replace(/"/g, "")
            ).split(',');
            // Only replace when decoded data is of type image/svg+xml
            if(backgroundSvg[0].indexOf("image/svg+xml")>-1) {
                $element.html(backgroundSvg[1]);
                $element.css("background-image", "none");
            }

        }
    };
});
```

**Comment by dominikwilkowski** [comment]
What's the browser support you guys have? You could use an SVG sprite in the DOM and reference that without any js. No IE8 though

**Comment by jharris-westpac** [comment]
Hi Dom, 

Yes that was the issue, if we just placed the SVG directly in the DOM, then there wasnt any point in using the grunticon loader which has the brower support fallback options of PNG background and PNG link. We have to support IE8 :)  We can always dream of the day customers get off IE or get on the Edge.

**Comment by dominikwilkowski** [comment]
;) you know it.

Anyway for now grunticon works 90% of the time with SPQ being a bit of a rouble kid. How are you feeling about it now with this solution you got here?

**Comment by tonytwong** [comment]
The proposed code I have put up would ensure that if the png/fallback css file is loaded (non SVG browsers - which I assume grunticon library is checking for) then the directive will do nothing when asked to embed.

**Comment by tonytwong** [comment]
@jharris-westpac great solution by the way

**Comment by jharris-westpac** [comment]
@tonytwong :+1:  I will implement your updated solution.

**Comment by jharris-westpac** [comment]
@dominikwilkowski It's all working fine in a new simple forms project, however I had to take @tonytwong advice and not use the JS components (modals, tooltips, tabs, accordians etc) and instead replace them with UI bootstrap versions and then style them like GUI 2. I did try hard to get HTML in UI bootstrap to match GUI 2 but the CSS used has gone beyond basic styling and using psudo selectors and layers which are conflicting and I just couldn't get it to work.   

Also because so much has changed, I decided to refactor the form layout, as the forms.css was getting a bit out of date and the markup a bit dodgy for things like the header and footer on the page. I also wanted a less version and hope to match the form master PDF design specs exactly. 

What we will need then is a full understanding of what HTML changes are needed for accessibility in Bootstrap 3 which were made in GUI 2. e.g. a diff between GUI 1 and 2 markup so we can make those in our UI bootstrap templates. I would also like your thoughts on hardware / software we can use to test accessibility? I want to start doing proper testing of it on my dev environment.

**Comment by dominikwilkowski** [comment]
No worries @jharris-westpac 
UI bootstrap is not accessible and therefor not GUI compliant but I am very happy to support you in any way to get you there.

We got a testing lab up here with around 20 devices and we had a proper accessibility report done on the GUI 2.0. Let me know if you want to meet.

**Comment by tonytwong** [comment]
@dominikwilkowski, can you elaborate on what specifically was changed (which components in UI-bootstrap) to make it more accessible.

**Comment by dominikwilkowski** [comment]
Not really as the UI-bootstrap is not accessible in the first place. For that we would need to look at the HTML difference between those six modules.

Please note that we are only talking about the following modules:
- alerts
- buttons
- modals
- popovers
- tabcordions
- tooltips

All other modules UI-bootstrap may have is not GEL and GUI and totally up to the project to use. The rest of the GUI modules don't require JS and should work in any SPA with the notable exception of grunticon.

Let me know if you would like to meet and talk about how best to find the differences.

Cheers

**Comment by jharris-westpac** [comment]
Started a new thread to keep it on topic https://github.com/WestpacCXTeam/GUI-angular/issues/2
